version: '3.9'

services:
  node_server:
    container_name: node_container
    image: myapp:v2
    build: 
      context: .
    ports:
      - "4000:4000"
    environment:
      - EXTERNAL_PORT=4000
      - PGDATABASE=metrobuses_db
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=portgres_db
      - GOOGLEMAPSKEY=AIzaSyCZgr16JUc3aW1jeuYam3FaWHW89PfY08Q
    depends_on:
      - portgres_db
  
  portgres_db: 
    container_name: portgres_db
    image: "postgres:12"
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=metrobuses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
