version: '3.9'

services:
  node_server:
    container_name: node_container
    image: myapp:v2
    build: 
      context: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - EXTERNAL_PORT=4000
      - PGDATABASE=metrobuses_db
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=postgres_db
      - GOOGLEMAPSKEY=AIzaSyCZgr16JUc3aW1jeuYam3FaWHW89PfY08Q
      - VEHICLESAPI=https://datos.cdmx.gob.mx/api/3/action/datastore_search?resource_id=ad360a0e-b42f-482c-af12-1fd72140032e&limit=3
    depends_on:
      - portgres_db
  
  portgres_db: 
    container_name: postgres_db
    image: "postgres:12"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=metrobuses_db
    volumes:
      - /postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
