version: '3.9'

services:
  node_server:
    container_name: node_container
    image: myapp:v1
    build: 
      context: .
    ports:
      - "4000:4000"
    environment:
      - EXTERNAL_PORT=4000
